name: stawi
description: Chat with your friends.
publish_to: 'none'
# On version bump also increase the build number for F-Droid
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.11
  app_links: ^6.4.0
  archive: ^4.0.4
  async: ^2.11.0
  badges: ^3.1.2
  blurhash_dart: ^1.2.1
  chewie: ^1.8.1
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  cupertino_icons: any
  desktop_drop: ^0.5.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^11.3.0
  dynamic_color: ^1.7.0
  emoji_picker_flutter: ^4.3.0
  emojis: ^0.9.9
  #fcm_shared_isolate: ^0.2.0
  file_picker: ^9.0.2
  file_selector: ^1.0.3
  flutter_cache_manager: ^3.4.1
  flutter_currency_picker: ^1.7.0
  flutter_foreground_task: ^8.17.0
  flutter_highlighter: ^0.1.1
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.3
  flutter_map: ^8.1.0
  flutter_new_badger: ^1.1.1
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0
  flutter_secure_storage: ^9.2.2
  flutter_shortcuts_new: ^2.0.0
  flutter_typeahead: ^5.2.0
  flutter_web_auth_2: ^5.0.0-alpha.0 # Version 4 blocked by https://github.com/MixinNetwork/flutter-plugins/issues/379
  flutter_webrtc: ^0.13.1
  geolocator: ^13.0.1
  go_router: ^14.3.0
  handy_window: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.1.0
  intl: any
  just_audio: ^0.9.39
  latlong2: ^0.9.1
  linkify: ^5.0.0
  matrix: ^0.38.0
  mime: ^2.0.0
  native_imaging: ^0.2.0
  opus_caf_converter_dart: ^1.0.1
  package_info_plus: ^8.0.2
  pasteboard: ^0.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  pretty_qr_code: ^3.2.1
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner_plus: ^2.0.10+1
  qr_image: ^1.0.0
  receive_sharing_intent: ^1.8.1
  record: ^5.1.2
  scroll_to_index: ^3.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.5.2
  slugify: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  sqlcipher_flutter_libs: ^0.6.1
  swipe_to_action: ^0.3.0
  tor_detector_web: ^1.1.0
  unifiedpush: ^5.0.1
  unifiedpush_ui: ^0.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  video_compress: ^3.1.4
  video_player: ^2.9.2
  wakelock_plus: ^1.2.2
  webrtc_interface: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.5
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  license_checker: ^1.6.0
  msix: ^3.6.2
  translations_cleaner: ^0.0.5

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash_logo_black.png"
  color_dark: "#121212"
  image_dark: "assets/splash_logo.png"
  android_12:
    image: "assets/splash_logo_black.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/splash_logo.png"
    icon_background_color_dark: "#121212"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

msix_config:
  display_name: Stawi
  publisher_display_name: Ant Investor Ltd
  publisher: CN=antinvestor, O=Ant Investor Ltd, L=Matrix, S=Internet, C=EU
  identity_name: com.antinvestor.stawi
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: stawi.antinvestor.com
  execution_alias: stawi
  sign_msix: false
  install_certificate: false


